apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
spec:
  containers:
  - name: fluentd-elasticsearch
    image: gcr.io/google_containers/fluentd-elasticsearch:1.8
    resources:
      limits:
        cpu: 100m
    env:
    - name: "FLUENTD_ARGS"
      value: "-vv"
    volumeMounts:
    - name: varlog
      mountPath: /varlog
    - name: containers
      mountPath: /var/lib/docker/containers
    - name: config-file
      mountPath: /etc/td-agent/td-agent.conf
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
  - name: config-file
    hostPath:
      path: /opt/custom/fluentd.conf

